name: Manual workflow to search PDFs for string

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:      
      search_string:        
        description: 'String to search for in PDFs'      
        required: true        
        default: 'Ruben'
        type: string
        
      periodico_num:
        description: 'Periodico number to search for PDFs'
        required: true
        default: '201'
        type: string

jobs:        
  search_pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests PyPDF2

      - name: Run PDF search
        run: |
          python busca_texto_en_periodico.py "${{ github.event.inputs.search_string }}"
