name: Manual workflow to search PDFs for string

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:      
      search_string:        
        description: 'String to search for in PDFs'      
        required: true        
        default: 'Ruben'
        type: string
        
      periodico_num:
        description: 'Periodico number to search for PDFs'
        required: true
        default: '201'
        type: string

      email_to:
        description: 'Email addresses to send results to (comma-separated)'
        required: true
        default: 'arriagar@gmail.com,breangelita@gmail.com'
        type: string

  schedule:
    # Run the workflow Monday through Friday at 9:00 AM CST
    - cron: '0 15 * * 1-5'

jobs:        
  search_pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests PyPDF2 pycryptodome

      - name: Get last successful periodico number
        id: last_periodico
        run: |
          # Get the value of the periodico_num input from the last successful run
          last_run_periodico=$(curl -H "Accept: application/vnd.github+json" \
                              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                              https://api.github.com/repos/${{ github.repository }}/actions/runs?event=workflow_dispatch | \
                              jq -r '.workflow_runs[0].inputs.periodico_num')
          
          # Increment the periodico number for the next run
          next_periodico=$((last_run_periodico + 1))
          echo "::set-output name=next_periodico::$next_periodico"

      - name: Run PDF search
        run: |
          python busca_texto_en_periodico.py "${{ github.event.inputs.search_string }}" "${{ steps.last_periodico.outputs.next_periodico }}"

      - name: Email search results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL_USER}}
          password: ${{secrets.EMAIL_PASS}}
          subject: PDF Search Results
          body: The search for "${{ github.event.inputs.search_string }}" in periodico ${{ steps.last_periodico.outputs.next_periodico }} is complete.
          to: ${{ github.event.inputs.email_to }}
          from: GitHub Actions
          content_type: text/plain
          attachments: |
            search_results.txt
