name: Manual workflow to search PDFs for string

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:      
      search_string:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'String to search for in PDFs'
        # Input has to be provided for the workflow to run
        required: true
        # Default value if no value is explicitly provided
        default: 'Ruben'
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:        
  search_pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests PyPDF2

      - name: Run PDF search
        run: |
          python busca_texto_en_periodico.py "${{ github.event.inputs.search_string }}"
